#
# Copyright (C) 2024 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
DEVICE_PATH := device/sts/a05bd

USE_XML_AUDIO_POLICY_CONF := 1
BOARD_SEPOLICY_DIRS += device/sts/a05bd/sepolicy
TARGET_BUILD_64BIT := true
TARGET_OTA_ASSERT_DEVICE := TAB-A05-BD
BOARD_VNDK_VERSION := current
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true
AB_OTA_UPDATER := false

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_IS_64_BIT := true
TARGET_USES_64_BIT_BINDER := true
TARGET_USES_32_BIT_BINDER := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a05bd
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 240
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=eng androidboot.console=ttyMT0 earlycon=uart8250,mmio32,0x11002000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_CONFIG := a05bd_defconfig
TARGET_KERNEL_SOURCE := kernel/sts/a05bd

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
    TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/kernel
    BOARD_PREBUILT_DTBOIMAGE := device/sts/a05bd/prebuilts/dtbo.img
endif

# Partitions
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 23592960
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_VENDORIMAGE_PARTITION_SIZE := 419430400
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_DTBO_PARTITION_SIZE := 8388608
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USES_REMOUNT := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BUILD_BROKEN_DUP_RULES := true

# Platform
TARGET_BOARD_PLATFORM := mt8168
TARGET_BOARD_PLATFORM_GPU := Mali-G52 MP1

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop


# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt8168
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
RECOVERY_SDCARD_ON_DATA := true

# Security patch level
PLATFORM_SECURITY_PATCH := 2021-06-05
VENDOR_SECURITY_PATCH := 2021-06-05

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# VINTF
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml
include vendor/sts/a05bd/BoardConfigVendor.mk

# Test.....
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
BOARD_ROOT_EXTRA_FOLDERS := mnt
BOARD_USE_LMKD := true
SELINUX_IGNORE_NEVERALLOWS := true
PRODUCT_TARGET_VNDK_VERSION := 28
BOARD_BUILD_PRODUCT_IMAGE := false
BOARD_HAVE_WIFI := true
BOARD_HAS_WIFI := true
BOARD_HAS_NFC := false
BOARD_USES_NFC := false
TARGET_USES_NFC := false
